# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
    buildPlatform: 'Any CPU'
    buildConfigurtion: 'Debug'
    soultion: '**/krugert.name-sorter.sln'
    project: '**/krugert.name-sorter.csproj'


steps:
- task: NuGetToolInstaller@1
  name: "NuGetToolInstaller"
  displayName: "NuGet Tool Installer"


- task: NuGetCommand@2
  name: "NuGetRestore"
  displayName: "NuGet Restore Packages"
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: 'select'


- task: DotNetCoreCLI@2
  name: "Tests"
  displayName: "Run Tests"
  inputs:
    command: 'test'
    projects: '$(Parameters.projects)'
    arguments: '--configuration $(BuildConfiguration)'



- task: DotNetCoreCLI@2
  name: "Publish"
  displayName: "Publish"
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: 'configuration: $(BuildConfiguration) --output: $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false


- task: PublishBuildArtifacts@1
  name: "PublishBuildArtifacts"
  displayName: "Publish build artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'AzureTestProject'
    publishLocation: 'Container'



